twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - 'form/custom_file_type.html.twig'
        - 'form/custom_form_type.html.twig'
    paths:
        '%kernel.project_dir%/public/email/css': email_css
        '%kernel.project_dir%/public/email/images': email_image
    globals:
        agence:
            name: Dawan Lille
            address: 46 rue des canonniers 59800 Lille

when@test:
    twig:
        strict_variables: true
